### PR TITLE
Create docker-publish.yml

### PR DESCRIPTION
**Pull request by bio-boris**
Lets update this to the behavior  that we want

### CODE REVIEW

**Comment by Xiangs18** [comment]
so secrets.GHCR_USERNAME and secrets.GHCR_TOKEN are not setup in iji-kbase and that's why we use this instead?

**Comment by MrCreosote** [comment]
A couple questions
* It seems like this is building on merge only - it is possible to set things up to build on PR like the other repos?
* How would we do release builds like https://github.com/kbase/auth2/blob/develop/.github/workflows/release-main.yml

**Comment by bio-boris** [comment]
Sorry, I missed these questions. I will look into it

**Comment by Xiangs18** [comment]
> so secrets.GHCR_USERNAME and secrets.GHCR_TOKEN are not setup in iji-kbase and that's why we use this instead?

If that's the case, why cannot we just set thing up in iji-kbase?

**Comment by bio-boris** [comment]
There are already tokens available and it is less tokens for us to maintain

**Comment by bio-boris** [comment]
Sorry @Xiangs18 I should have deleted this PR instead of merging it!

**Pull request merged**
